module.exports = [
  "Will enjoys playing chess.",
  "As an early actor on 'The Fresh Price of Bel-Air' Will would memorize the entire script and lip everyone's lines while filming.",
  "For one of Jada Pinkett Smith's birthdays, Will Smith created a DVD message telling his wife there were clothes upstairs and a car would pick her up in 20 minutes. She was taken to the airport and flown to San Francisco, where Will was waiting for her at a restaurant she'd been reading about. He told PEOPLE, 'That's how Big Will does it!'",
  "'We are who we choose to be.' - Will Smiff",
  "Smiff attended Overbrook High School in West Philadelphia for the majority of his high school years. However, he also spent a short time attending Archbishop John Carroll High School in Radnor.",
  "Smith has been married twice. His first marriage in 1992 lasted only three years but produced a son, Willard Smith III, who is also known as Trey.",
  "Will Smith could bench 385 pounds while filming I, Robot",
  "A millionaire by age 20, Will Smith admits to spending lavishly on jewelry, a house and luxury cars early in his career. He and his buddies once convinced the salespeople at Gucci to close the store so they could enjoy a private shopping spree. 'Being able to buy anything you want makes you a little crazy,' Smith later told PEOPLE.",
  "Will Smith turned down MIT to pursue a music career",
  "Known for his boundless confidence, Will Smith was worried about making the leap from rapper to actor. When called in to audition for The Cosby Show and A Different World, Smith was a no-show. 'I realized later how scared I was to take that step,' he told PEOPLE.",
  "Will Smith speaks fluent Spanish",
  "Will Smith paid for each of his Fresh Prince of Bel-Air costars to upgrade their onset dressing rooms in 1995. 'Mine was called Daphne's little bordello,' Daphne Maxwell Reid, who played Smith's Aunt Viv, told PEOPLE. 'It had a gold brocade chair with cupids on it.'",
  "Will Smith turned down the role of Neo in The Matrix",
  "Will Smith wrote the children's book Just the Two of Us",
  "Will Smith met wife Jada Pinkett Smith when she tried out for the role of his girlfriend on 'The Fresh Prince of Bel-Air' (1990). The role eventually went to Nia Long.",
  "Will Smith has three children. Son, Willard Smith III (Trey Smith) born in November 11, 1992, with Sheree Fletcher. Son, Jaden Christopher Syre Smith (Jaden Smith) born July 8, 1998 and daughter, Willow Camille Reign Smith (Willow Smith) born October 31, 2000 with Jada Pinkett Smith.",
  "Will Smith has said he based his character Captain Steven Hiller in Independence Day (1996) on his favorite big screen hero, Harrison Ford, most notably his performances of Han Solo in Star Wars (1977) and its sequels.",
  "Will's siblings are: Pam Smith (born in 1964), and twins Ellen and Harry Smith (born in 1971).",
  "Will Smith won a Grammy Award for the song 'Summertime' during his rap career.",
  "Will Smith received the first ever Grammy Award for Best Rap Performance, for the song 'Parents Just Don't Understand' in 1989 with his partner Jeffrey A. Townes (aka Jazzy Jeff).",
  "Will Smith was chosen by People magazine as one of the 50 Most Beautiful People in the World. [1998]",
  "Smith's pilot test show for 'The Fresh Prince of Bel-Air' (1990) was directed by Debbie Allen.",
  "Will Smith met his first wife, Sheree Fletcher, at a taping of 'A Different World' (1987) in 1991.",
  "As a public role model, Will Smith hosted the Presidential Inaugural Celebration for Youth, as part of the Gala for President Bill Clinton. [January 1993]",
  "Will Smith is a graduate of Philly's legendary Overbrook High School, whose alumni include Wilt Chamberlain, Hal Lear, Wali 'Wonder' Jones, Walt Hazzard, The Dovells, The Orlons, DeeDee Sharp, etc. and, in tribute to his student years there, his production company is called Overbrook Entertainment.",
  "Will Smith attended the prestigious Julia Reynolds Masterman Laboratory and Demonstration School in Philadelphia.",
  "Will Smith turned down the role of Neo in The Matrix (1999).",
  "Will Smith is the first hip-hop artist to be nominated for an Academy Award.",
  "Will Smith speaks fluent Spanish.",
  "Will Smith is ranked #2 on Star TV's Top Ten Box Office stars of the 1990s (2003).",
  "Will Smith had a chart-hit together with DJ Jazzy Jeff (aka Jeffrey A. Townes.)",
  "Will Smith dropped from Columbia Records as an artist after lackluster sales of his third solo album, which was self-titled, and greatest hits compilation. [Summer 2003]",
  "Will Smith incorporates the line 'Aw, hell no!' into all his movies as a running catch phrase like Arnold Schwarzenegger's 'I'll be back!'.",
  "Will Smith is ranked #15 in TV Guide's list of 'TV's 25 Greatest Teen Idols' (23 January 2005 issue).",
  "Will Smith gained a place in the Guinness World Records book for most public appearances in 12 hours, by attending three red carpet 'premieres' for Hitch (2005/I) on 22nd February 2005. He walked the red carpet and introduced the film at Manchester, Birmingham, and finally for the premiere in London, England.",
  "Will Smith once stated that in his whole career, he most regrets turning down the part of Neo in The Matrix (1999) and the film that he most regrets making was Wild Wild West (1999).",
  "Will Smith has been at his adult height of 6' 2 since he was 13, although he is now about 60 pounds heavier than he first was when he reached this height.",
  "Premiere Magazine ranked Will Smith as #44 on a list of the Greatest Movie Stars of All Time in their Stars in Our Constellation feature (2005).",
  "Will Smith sang a few lines 'Wild Wild West' to his on screen cousin Carleton, a movie in which he starred 6 years later.",
  "Will Smith hosted the MTV Movie Awards in 1994.",
  "Will Smith considered for the role of 'Mr. Smith' in Mr. & Mrs. Smith (2005) before Brad Pitt was cast.",
  "Will Smith is supposedly a huge fan of the Swedish well-known (but barely known in the U.S.) melodic heavy metal band Soilwork.",
  "Will Smith is ranked #66 in VH1's 100 greatest Teen Stars.",
  "Will Smith holds the record for most Kids Choice Awards with a whopping six wins.",
  "Will Smith is ranked #14 on Premiere's 2006 'Power 50' list. Had ranked #18 in 2005. He is the second-highest ranked actor, behind only Tom Cruise.",
  "Will Smith and Jada Pinkett Smith were forced to leave their home in California because a bush fire threatened to destroy it and several other houses in the same area. [October 2005]",
  "Will Smith's 1995 divorce from ex-wife Sheree Fletcher led to a $900,000 lump sum divorce settlement for Zampino plus $24,000 per month in alimony and child support; this equals $288,000 a year.",
  "Will Smith lost his place in the Guiness World Records book for most public appearances in 12 hours to German actors Jürgen Vogel and Daniel Brühl, who attended four red carpet premieres of their movie Ein Freund von mir (2006), one more than Will (22 October 2006).",
  "In the 1998 rap lyrics of 'Gettin' Jiggy', Will Smith says that Muhammad Ali would call him 'The Greatest.' Two and a half years later, he played the title role in Ali (2001).",
  "An animated caricature of Will Smith appeared in 'Men in Black: The Series' (1997) (the animated series adaptation of Men in Black (1997)), alongside a caricature of his MIB co-star Tommy Lee Jones, set against a shot that parodied one of the famous low angle shots of a building being threatened by a flying saucer, an in-joke reference to Smith's 1996 hit 'Men in Black: The Series' (1997), which preceded Men in Black (1997).",
  "Will Smith's character from Men in Black (1997), Agent Jay, was not originally written to specifically be a black man. In fact, the role was offered to Caucasian actors Chris O'Donnell and David Schwimmer before Smith accepted the part.",
  "Will Smith had to undergo treatment on his shoulder in a New York hospital after he suffered a strain. [March 2007]",
  "Will Smith was among the guests at Tom Cruise's and Katie Holmes's wedding ceremony in Italy.",
  "Will Smith was ranked #30 on VH1's 50 Greatest Hip Hop Artists along with DJ Jazzy Jeff & The Fresh Prince.",
  "Will Smith ranked #29 on VH1's 100 Sexiest Artists.",
  "In 2007, Will Smith ranked #5 on Entertainment Weekly's The 50 Smartest People in Hollywood.",
  "December 2007 - According to Forbes, for each dollar he got paid, Smith's movies averaged $10 of gross income.",
  "Will Smith was a millionaire before the age of 20.",
  "In 2004, Will Smith's net worth was estimated to be $188 million.",
  "In 2007, Forbes Magazine estimated Will Smith's earnings for the year at $31 million.",
  "Will Smith is good friends with Ken Foree.",
  "Will Smith is a huge fan of Professional Wrestling.",
  "Will Smith is often called 'Mr. July' by the media due to the fact that most of his summer blockbusters open in July.",
  "As of Hancock (2008), Will Smith holds the record for the actor to star in the most consecutive $100 million-grossing movies (8).",
  "Will Smith and his daughter Willow Smith both had movies opening 2 July, 2008. His was Hancock (2008), hers was Kit Kittredge: An American Girl (2008).",
  "Will Smith has appeared in two films starting with the word 'I', I, Robot (2004) and I Am Legend (2007).",
  "Will Smith wrote and performed the song, 'Just the Two of Us', about his first son, Trey Smith.",
  "Will Smith was considered for the role of Detective James Carter in Rush Hour (1998).",
  "Will Smith holds the record of appearing in the most consecutive $100 million-grossing movies (8).",
  "Will Smith was in consideration for the part of Curtis Taylor Jr in Dreamgirls (2006). However Jamie Foxx was cast instead.",
  "Will Smith's Birth Card is the Queen of Hearts.",
  "Will Smith has solved Rubik's cubes in both The Fresh Prince of Bel Air and The Pursuit of Happiness. This is a real talent of his; he has shown on live TV that he can solve a Rubik's Cube in under 55 seconds.",
  "The Bridge On The River Kwai is Will Smith's favorite movie."
];
